"""
Django settings for grocery_website project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kc$0xul2m1l013bpz3a!vnvibs897dmbyy+#f+nm7=p(096edc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'grappelli.dashboard',
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store'
]

# Grappelli settings
GRAPPELLI_ADMIN_TITLE = 'Grocery Store Administration'
GRAPPELLI_INDEX_DASHBOARD = 'grocery_website.dashboard.CustomDashboard'

# Grappelli customization
GRAPPELLI_SWITCH_USER = True
GRAPPELLI_CLEAN_INPUT_TYPES = True

# Admin site customization
ADMIN_SITE_HEADER = "Grocery Store Admin"
ADMIN_SITE_TITLE = "Grocery Store Portal"
ADMIN_INDEX_TITLE = "Welcome to Grocery Store Admin Portal"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'grocery_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'grocery_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'store/static'),
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Serve static files in development
if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'store/static'),
    ]
    STATIC_ROOT = None
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'store.RegisterUser'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Login/Logout URLs
LOGIN_URL = 'loginpage'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Message Framework
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Django Suit configuration
SUIT_CONFIG = {
    'ADMIN_NAME': 'Grocery Store Admin',
    'HEADER_DATE_FORMAT': 'l, j. F Y',
    'HEADER_TIME_FORMAT': 'H:i',
    'SHOW_REQUIRED_ASTERISK': True,
    'CONFIRM_UNSAVED_CHANGES': True,
    'SEARCH_URL': '',
    'MENU_ICONS': {
        'auth': 'icon-lock',
        'store': 'icon-shopping-cart',
    },
    'MENU_OPEN_FIRST_CHILD': True,
    'MENU_EXCLUDE': ('auth.group',),
    'MENU': (
        {'label': 'Store', 'icon': 'icon-shopping-cart', 'models': (
            {'model': 'store.Category', 'label': 'Categories'},
            {'model': 'store.Product', 'label': 'Products'},
            {'model': 'store.Order', 'label': 'Orders'},
            {'model': 'store.Cart', 'label': 'Carts'},
        )},
        {'label': 'Users', 'icon': 'icon-user', 'models': (
            {'model': 'store.RegisterUser', 'label': 'Users'},
            {'model': 'store.Address', 'label': 'Addresses'},
        )},
        {'label': 'Content', 'icon': 'icon-picture', 'models': (
            {'model': 'store.attacarousel', 'label': 'Carousel'},
            {'model': 'store.ProductReview', 'label': 'Reviews'},
        )},
    ),
}
